### ISSUE TITLE
please move libcdms build#6 from 'main' to 'broken' in conda-forge

### ISSUE THREAD

**Issue by muryanto1** [conda-forge/libcdms-feedstock#28]
Hi @conda-forge/core,

Please move libcdms build#6 from main to broken on the conda-forge channel on anaconda.org
because we have a list of packages that depend on libcdms, and we would like to test the changes that picks up new libnetcdf 4.7.1 locally first, and upload to our own cdat/label/nightly channel, validate all dependent packages. Only after we finish our validation, we will then want to rebuild libcdms-feedstock and upload our packages to conda-forge

**Comment by CJ-Wright** [comment]
Is there an error with the package?
Have you considered using https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#downstream-tests

**Comment by muryanto1** [comment]
There is no error with the package, but the latest conda-forge/cdms2 packages we built (build#3) -- https://anaconda.org/conda-forge/cdms2/files (was built with libnetcdf 4.6.2). but the recipe in the feedstock has:
  host:
    - python {{ python }}
    - setuptools
    - cdat_info >=8.2
    - numpy
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - cdtime >=3.1.2
    - openblas
    - lazy-object-proxy
    - libnetcdf
  run:
    - python {{ python }}
    - libcf
    - distarray
    - lazy-object-proxy
    - cdtime
    - cdat_info >=8.2
    - {{ pin_compatible('numpy') }}
    - esmf
    - esmpy
    - six
    - libcdms >=3.1.2
    - libdrs_f >=3.1.2
    - libdrs >=3.1.2
    - cdtime >=3.1.2
    - openblas
    - libnetcdf


so when we install cdms2 now, it is picking up libdrs build#5 that was built with libnetcdf 4.7.1.
I am guessing that we should not have the ">=" for libcdms, libdrs_f, libdrs and cdtime in the cdms2 recipe. Is that correct? because if I install cdms2 that was built with libnetcdf 4.6.2, I want to pick up libcdms that was also built with 4.6.2.

our organization maintains:
libcf
libdrs
libcdms
libdrs_f
cdat_info
cdtime
cdms2
...
in that order of dependency.
we are not ready to move to libnetcdf 4.7.1 (need to test it locally)..I am not sure if we can do downstream-tests.. our testsuite needs quite a bit of setup to be able to run in your CI

**Comment by muryanto1** [comment]
I would like to bump the version of the package to libcdms-3.1.3 when building with libnetcdf 4.7.1.
so I would like to request 3.1.2 build#6 to be labeled 'broken' or something not 'main'.
so that in my downstream packages I can pin libcdms to 3.1.2 since we can only run with libnetcdf 4.6.2 for now.

**Comment by ocefpaf** [comment]
@muryanto1 not sure I follow what you want to do here but the issue is closed now. Do you still want us to remove the package?

**Comment by muryanto1** [comment]
no need to remove the packages (or relabel the packages to be broken).
Please just ignore this issue.
